// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyE6w5pMR3n6txFds26ZJYe3cPFimW5sQ',
    appId: '1:441133021852:web:0b5f00905c1a824783cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    authDomain: 'foodautomation-1a2f8.firebaseapp.com',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
    measurementId: 'G-Q8BRT2GGTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjjc875pE34DyHsKbIn6m66xCPhMfpbE',
    appId: '1:441133021852:android:c6604e78aea80a1983cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXc0Ffca9GAyS5nMlY0i6Vw8nN4LKfr8',
    appId: '1:441133021852:ios:1ef48f03757c560383cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
    iosBundleId: 'com.example.avaliacaoToten',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXXc0Ffca9GAyS5nMlY0i6Vw8nN4LKfr8',
    appId: '1:441133021852:ios:1ef48f03757c560383cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
    iosBundleId: 'com.example.avaliacaoToten',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyE6w5pMR3n6txFds26ZJYe3cPFimW5sQ',
    appId: '1:441133021852:web:de6638ebd61dad0883cb59',
    messagingSenderId: '441133021852',
    projectId: 'foodautomation-1a2f8',
    authDomain: 'foodautomation-1a2f8.firebaseapp.com',
    storageBucket: 'foodautomation-1a2f8.firebasestorage.app',
    measurementId: 'G-KXX6J4YJC3',
  );
}
